import * as ElementPlusIconsVue from '@element-plus/icons-vue'
import type { Component } from 'vue'

/**
 * 图标名称映射表
 * 将数据库中存储的图标名称映射到 @element-plus/icons-vue 的组件名
 */
const iconMap: Record<string, string> = {
  // 系统管理
  'setting': 'Setting',
  'user': 'User',
  'peoples': 'UserFilled',
  'tree-table': 'Grid',
  'tree': 'Share',
  
  // 系统监控
  'monitor': 'Monitor',
  'server': 'Server',
  'form': 'Document',
  'logininfor': 'Tickets',
  
  // 系统工具
  'tool': 'Tools',
  'code': 'DocumentCopy',
  
  // 通用图标
  'home': 'HomeFilled',
  'menu': 'Menu',
  'list': 'List',
  'edit': 'Edit',
  'delete': 'Delete',
  'search': 'Search',
  'plus': 'Plus',
  'minus': 'Minus',
  'check': 'Check',
  'close': 'Close',
  'upload': 'Upload',
  'download': 'Download',
  'refresh': 'Refresh',
  'setting2': 'SetUp',
  'lock': 'Lock',
  'unlock': 'Unlock',
  'key': 'Key',
  'bell': 'Bell',
  'message': 'Message',
  'chat': 'ChatDotRound',
  'notification': 'Notification',
  'warning': 'Warning',
  'info': 'InfoFilled',
  'success': 'SuccessFilled',
  'error': 'CircleCloseFilled',
  'question': 'QuestionFilled',
  'arrow-left': 'ArrowLeft',
  'arrow-right': 'ArrowRight',
  'arrow-up': 'ArrowUp',
  'arrow-down': 'ArrowDown',
  'back': 'Back',
  'more': 'More',
  'star': 'Star',
  'star-filled': 'StarFilled',
  'heart': 'Heart',
  'heart-filled': 'HeartFilled',
  'view': 'View',
  'hide': 'Hide',
  'date': 'Calendar',
  'time': 'Clock',
  'location': 'Location',
  'phone': 'Phone',
  'email': 'Message',
  'link': 'Link',
  'image': 'Picture',
  'video': 'VideoCamera',
  'audio': 'Microphone',
  'file': 'Files',
  'folder': 'Folder',
  'document': 'Document',
  'pdf': 'Document',
  'excel': 'Document',
  'word': 'Document',
  'powerpoint': 'Document',
  'zip': 'Folder',
  'database': 'Coin',
  'chart': 'DataLine',
  'pie-chart': 'PieChart',
  'bar-chart': 'Histogram',
  'line-chart': 'TrendCharts',
  'table': 'Grid',
  'form2': 'EditPen',
  'button': 'Pointer',
  'input': 'Edit',
  'select': 'Select',
  'checkbox': 'Check',
  'radio': 'CircleCheck',
  'switch': 'Switch',
  'slider': 'Operation',
  'rate': 'Star',
  'color': 'Brush',
  'font': 'Font',
  'bold': 'Bold',
  'italic': 'Italic',
  'underline': 'Underline',
  'strikethrough': 'Strikethrough',
  'align-left': 'AlignLeft',
  'align-center': 'AlignCenter',
  'align-right': 'AlignRight',
  'indent': 'Indent',
  'outdent': 'Outdent',
  'list-ordered': 'List',
  'list-unordered': 'List',
  'code2': 'DocumentCopy',
  'terminal': 'Terminal',
  'bug': 'Warning',
  'fix': 'MagicStick',
  'optimize': 'TrendCharts',
  'deploy': 'Upload',
  'monitor2': 'DataLine',
  'log': 'Document',
  'permission': 'Lock',
  'role': 'UserFilled',
  'dept': 'OfficeBuilding',
  'dict': 'Collection',
  'config': 'Setting',
  'notice': 'Bell',
  'job': 'Suitcase',
  'gen': 'DocumentCopy',
  'swagger': 'Document',
  'druid': 'DataLine',
  'server2': 'Monitor',
  'cache': 'Coin',
  'connection': 'Connection',
  'cpu': 'Cpu',
  'memory': 'Coin',
  'disk': 'Coin',
  'network': 'Connection',
  'process': 'SetUp',
  'thread': 'SetUp',
  'jvm': 'Coin',
  'gc': 'Refresh',
  'heap': 'Coin',
  'stack': 'Coin',
  'class': 'Document',
  'method': 'Document',
  'interface': 'Document',
  'api': 'Document',
  'endpoint': 'Document',
  'request': 'Document',
  'response': 'Document',
  'header': 'Document',
  'body': 'Document',
  'cookie': 'Document',
  'session': 'Document',
  'token': 'Key',
  'jwt': 'Key',
  'oauth': 'Key',
  'sso': 'Key',
  'ldap': 'Key',
  'ad': 'Key',
  'cas': 'Key',
  'saml': 'Key',
  'openid': 'Key',
  'oidc': 'Key',
  'oauth2': 'Key',
  'basic': 'Key',
  'digest': 'Key',
  'bearer': 'Key',
  'api-key': 'Key',
  'secret': 'Key',
  'certificate': 'Key',
  'ssl': 'Lock',
  'tls': 'Lock',
  'https': 'Lock',
  'http': 'Link',
  'ftp': 'Link',
  'ssh': 'Lock',
  'telnet': 'Link',
  'smtp': 'Message',
  'pop3': 'Message',
  'imap': 'Message',
  'dns': 'Connection',
  'dhcp': 'Connection',
  'tcp': 'Connection',
  'udp': 'Connection',
  'ip': 'Connection',
  'mac': 'Connection',
  'vlan': 'Connection',
  'vpn': 'Lock',
  'proxy': 'Connection',
  'load-balancer': 'Connection',
  'firewall': 'Lock',
  'router': 'Connection',
  'switch2': 'Connection',
  'hub': 'Connection',
  'gateway': 'Connection',
  'bridge': 'Connection',
  'repeater': 'Connection',
  'modem': 'Connection',
  'antenna': 'Connection',
  'satellite': 'Connection',
  'fiber': 'Connection',
  'cable': 'Connection',
  'wireless': 'Connection',
  'bluetooth': 'Connection',
  'wifi': 'Connection',
  'nfc': 'Connection',
  'rfid': 'Connection',
  'gps': 'Location',
  'map': 'Location',
  'compass': 'Location',
  'navigation': 'Location',
  'route': 'Location',
  'direction': 'Location',
  'distance': 'Location',
  'speed': 'Location',
  'time2': 'Clock',
  'date2': 'Calendar',
  'calendar': 'Calendar',
  'schedule': 'Calendar',
  'event': 'Calendar',
  'reminder': 'Bell',
  'alarm': 'Bell',
  'timer': 'Clock',
  'stopwatch': 'Clock',
  'countdown': 'Clock',
  'duration': 'Clock',
  'interval': 'Clock',
  'frequency': 'Clock',
  'period': 'Clock',
  'cycle': 'Refresh',
  'loop': 'Refresh',
  'repeat': 'Refresh',
  'iterate': 'Refresh',
  'recursive': 'Refresh',
  'backtrack': 'Back',
  'forward': 'Right',
  'backward': 'Left',
  'up': 'Top',
  'down': 'Bottom',
  'left': 'Left',
  'right': 'Right',
  'top': 'Top',
  'bottom': 'Bottom',
  'center': 'Aim',
  'middle': 'Aim',
  'start': 'CaretRight',
  'end': 'CaretLeft',
  'begin': 'CaretRight',
  'finish': 'CaretLeft',
  'complete': 'CircleCheck',
  'done': 'CircleCheck',
  'finish2': 'CircleCheck',
  'complete2': 'CircleCheck',
  'done2': 'CircleCheck',
  'success2': 'SuccessFilled',
  'success3': 'SuccessFilled',
  'success4': 'SuccessFilled',
  'success5': 'SuccessFilled',
  'success6': 'SuccessFilled',
  'success7': 'SuccessFilled',
  'success8': 'SuccessFilled',
  'success9': 'SuccessFilled',
  'success10': 'SuccessFilled',
}

/**
 * 获取图标组件
 * @param iconName 图标名称（数据库中存储的名称）
 * @returns 图标组件或 undefined
 */
export function getIconComponent(iconName: string): Component | undefined {
  if (!iconName) return undefined
  
  // 先尝试直接匹配 PascalCase 组件名
  if ((ElementPlusIconsVue as any)[iconName]) {
    return (ElementPlusIconsVue as any)[iconName]
  }
  
  // 尝试从映射表中获取
  const mappedName = iconMap[iconName.toLowerCase()]
  if (mappedName && (ElementPlusIconsVue as any)[mappedName]) {
    return (ElementPlusIconsVue as any)[mappedName]
  }
  
  // 尝试将 kebab-case 转换为 PascalCase
  const pascalCase = iconName
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
  
  if ((ElementPlusIconsVue as any)[pascalCase]) {
    return (ElementPlusIconsVue as any)[pascalCase]
  }
  
  // 如果都找不到，返回 undefined
  console.warn(`图标 "${iconName}" 未找到对应的组件`)
  return undefined
}

/**
 * 检查图标是否存在
 * @param iconName 图标名称
 * @returns 是否存在
 */
export function hasIcon(iconName: string): boolean {
  return getIconComponent(iconName) !== undefined
}
